config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  # Home Page - Index
  root 'pages#index'

  # Signing in
  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"

  # Creating a new account
  get "/sign_up" => "users#new", as: "sign_up"
  post "/sign_up" => "users#new"

  # Current Users profile page
  get "/profile" => "users#profile" #own dashboard
  get "/profile/:id" => "users#profile/:id"

  # Get/Show create a listing page
  get "/listings/new" => "listings#new"

  get "/listings/autofill" => "listings#autofill"

  # Get search results
  post "/listings/search" => "listings#search", as: "search"
  get "/listings/search" => "listings#search_form", as:"search_form"

  # Get/Show individual listing page
  get "/listings/:id" => "listings#show"

  # Braintree Checkout Route incl. wildcard [T]
  post 'braintree/:booking_id/checkout' => 'braintree#checkout', as: 'braintree_checkout'


  # Get/Show new review page
  # get "/reviews/new" => "reviews#new"
  # post "/reviews/create" => "reviews#create"



  # Other Users profile page - looking at someone else's profile, basic information
  get "/users/:id" => "users#show"

  # Verifying a listing
  post "/verify/:id" => "listings#verify", as: "verify"

  # Google OAuth2.0 callback route
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, :bookings

  resources :listings do
    resource :review, only: [:new, :create, :destroy]
  end

  resources :bookings do
    resources :brain_tree_new
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :user
  validates :title, :description, presence: true
  mount_uploaders :images, ListingsImageUploader

  scope :title, -> (title) { where title: title}
  scope :country, -> (country) {where country: country}
  scope :city, -> (city) {where city: city}
  scope :beds, -> (beds) {where beds: beds}
  scope :bathrooms, -> (bathrooms) {where bathrooms: bathrooms}
  scope :amenities, -> (amenities) {where amenities: amenities}
  scope :property_type, -> (property_type) {where property_type: property_type}
  scope :price_per_night, -> (price_per_night) {where price_per_night: price_per_night}
  scope :maximum_guests, -> (maximum_guests) {where maximum_guests: maximum_guests}
  scope :multi, -> (values) { where("title iLike ? OR country iLike ? OR city iLike ? OR property_type iLIKE ?", "%#{values}%", "%#{values}%", "%#{values}%", "%#{values}%")}
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :require_login
    before_action :set_listing, only: [:show, :edit, :update, :destroy, :verify]
    before_action :check_user, only: [:edit, :update, :destroy]
    before_action :check_role, only: [:verify]

    def index
      # Use will_paginate. don't be a masochist.
      # p params[:page]
      @listings = Listing.all.order(created_at: :desc)
      @listingsPerPage = 10
      @listingsCount = Listing.all.count
      @paginate_count = (@listings.count/8).to_i
        # byebug
      if params[:page] == 1
        @listings = @listings.first(10)
      end
    end

    def autofill
      autofill = []
      autofill.uniq
      listings = Listing.multi(params[:searchvalue])
      listings.each { |l| autofill << l.property_type && autofill << l.country && autofill << l.title && autofill << l.city}

      render :json => autofill
    end

    def search_form
      @listings = Listing.all
      @paginate_count = (@listings.count/8).to_i
      render "listings/search"
    end

    def search
      @searchTerm = params[:listing][:multi]
      @listings = Listing.where(nil)
      # @listings = @listings.title(params[:listing][:title]) if params[:listing][:title].present?
      # @listings = @listings.country(params[:listing][:country]) if params[:listing][:country].present?
      # @listings = @listings.city(params[:listing][:city]) if params[:listing][:city].present?
      # @listings = @listings.property_type(params[:listing][:property_type]) if params[:listing][:property_type].present?
      @listings = @listings.multi(params[:listing][:multi]) if params[:listing][:multi].present?
      @listings = @listings.maximum_guests(params[:listing][:maximum_guests]) if params[:listing][:maximum_guests].present?
      # @listings = @listings.beds(params[:listing][:beds]) if params[:listing][:beds].present?
      # @listings = @listings.bathrooms(params[:listing][:bathrooms]) if params[:listing][:bathrooms].present?
      @listings = @listings.amenities(params[:listing][:amenities]) if params[:listing][:amenities].present?
      # @listings = @listings.price_per_night(params[:listing][:price_per_night]) if params[:listing][:price_per_night].present?

      # filtering_params(params).each do |key, value|
      #   @listings = @listings.public_send(key, value) if value.present?
      # end

      @paginate_count = (@listings.count/8).to_i
      # byebug
      respond_to do |response|
        response.html {render "listings/search"}
        response.js
      end
    end

    def show
      # @review = Review.find(params[:id]).order(created_at: :desc)
      # @review = Review.find_by(params[:id])
      # @review = Review.all.order(created_at: :desc)
      @reviews = Review.where(listing_id: params[:id])
    end

    def create
      @listing = Listing.new(listing_params)
      @listing.user_id = current_user.id
      if @listing.save
        flash[:success] = "You listing was successfully created"
        redirect_to listings_path
      else
        @listing.errors.full_messages.each_with_index do |e,i|
          key = "error" + i.to_s
        flash[key] = e
        end
        redirect_to new_listing_path
      end
      # flash[:error0] => "title_not null"
      # flash[:error1] => "location not null"
    end

    def new
    end

    def edit
    end

    def update
      @listing.update(listing_params)
      if @listing.save
        redirect_to listings_path
      else
        redirect_to listings_path
      end
    end

    def destroy
      if @listing.destroy
        redirect_to listings_path
      else
        redirect_to listings_path
      end
    end

    def verify
      if @listing.verified
        @listing.update(verified: false)
      else
        @listing.update(verified: true)
      end

      if @listing.save
        flash[:success] = "Listing was successfully Verifed/Unverified"
        redirect_to listings_path
      end
    end

    private

    def set_listing
      @listing = Listing.find(params[:id])
    end

    def listing_params
      params.require(:listing).permit(:title, :description, :maximum_guests,
                                      :price_per_night, :home_type, :property_type,
                                      :country, :street_address, :room_number,
                                      :city, :state, :zip_code, :beds, :bathrooms,
                                      :property_type, amenities:[], shared_spaces:[], images: [])
    end

    def check_user
      @listing = Listing.find(params[:id])
      if @listing.user == current_user || current_user.moderator? || current_user.superadmin?
      else
          flash[:alert] = "You are not authorized to perform that action."
          redirect_to listings_path
      end
    end

    def check_role
      if current_user.customer?
        flash[:alert] = "You are not authorized to perform that action."
        redirect_to listings_path
      end
    end

    def filtering_params(params)
      params.require(:listing).permit(:title, :country, :property_type, :city, :multi, :maximum_guests, :beds, :bathrooms, :amenities, :price_per_night)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_all_listings.html.erb
<h1 class="m-3">Recent Listings</h1>

  <% @listings.each do |listing| %>
  <a target="_blank" href="<%= listing_path(listing.id) %>" aria-hiddden="true">
  <div class="card-deck d-inline-block m-2">
    <div class="card border-0" style="width: 18.5rem;">

      <div id="carouselExampleFade<%= listing.id %>" class="carousel slide carousel-fade" data-ride="carousel" data-interval="false">
        <div class="carousel-inner">
          <% listing.images.each_with_index do |image, i| %>
            <div class="carousel-item <%= "active" if i == 0 %>">
              <img class="d-block w-100" src="<%= image.url %>" alt="First slide">
            </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleFade<%= listing.id %>" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleFade<%= listing.id %>" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </a>
      <div class="card-body">
        <div class="d-flex">
          <h5 class="card-title"><%= truncate(listing.title, length: 20) %></h5>
          <% if listing.verified == true %>
            <span class="badge badge-success d-inline-block h-100 mt-1 ml-2">Verified</span>
          <% end %>
        </div>
        <p class="card-text" style="font-size: 14px;"><%= truncate(listing.property_type, length: 75) %></p>

        <div class="d-flex">
          <!-- <a href= "<%#=listing_path(listing.id)%>" class="btn btn-outline-primary btn-sm mb-3 d-inline">Read More</a></br> -->
          <% if current_user && current_user.superadmin? %>
            <% if listing.verified == false %>
              <%= link_to "Verify", verify_path(listing.id), method: :post, class: "btn btn-success btn-sm d-inline h-100" %>
            <% else %>
              <%= link_to "Un-verify", verify_path(listing.id), method: :post, class: "btn btn-dark btn-sm d-inline h-100" %>
            <% end %>
          <% end %>
        </div>

        <p class="card-text"><i class="fas fa-dollar-sign"></i> <strong>Price per Night:</strong> <%= listing.price_per_night %>0 RM</p>
        <p class="card-text"><i class="fas fa-users"></i> <strong>Max Guests:</strong> <%= listing.maximum_guests %></p>
        <% if current_user && (current_user.id == listing.user_id || current_user.moderator?) %>
          <%= link_to "Edit", edit_listing_path(listing.id), class: "btn btn-warning btn-sm mr-1" %>
          <%= link_to "Delete", listing_path(listing.id), class: "btn btn-danger btn-sm", method: :delete, :data => {:confirm => 'Are you sure you want to delete this listing?'} %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>

<div class="container d-flex justify-content-center mb-3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
      <div class="d-flex">
        <% count = 0 %>
        <% @paginate_count.times do %>
        <% count += 1 %>
        <li class="page-item"><a class="page-link" href="/?page=<%= count %>"><%= count %></a>
        <% end %>
      </div>
      <li class="page-item"><a class="page-link" href="/?page=<%= +1 %>">Next</a></li>
    </ul>
  </nav>
</div>

app/views/listings/_form.html.erb
<div class="text-field">
  <%= form.label :title %>
  <%= form.text_field :title, class:"form-control"%></br>
</div>

<div class="text-area">
  <%= form.label :description %>
  <%= form.text_area :description, class:"form-control", rows:"10" %></br>
</div>

<div class="text-field">
  <%= form.label :price_per_night %>
  <%= form.text_field :price_per_night, class:"form-control" %></br>
</div>

app/views/listings/_search.html.erb
<% @listings.each do |listing| %>
<a target="_blank" href="<%= listing_path(listing.id) %>" aria-hiddden="true">
<div class="card-deck d-inline-block m-2">
  <div class="card border-0" style="width: 18.5rem;">

    <div id="carouselExampleFade<%= listing.id %>" class="carousel slide carousel-fade" data-ride="carousel" data-interval="false">
      <div class="carousel-inner">
        <% listing.images.each_with_index do |image, i| %>
          <div class="carousel-item <%= "active" if i == 0 %>">
            <img class="d-block w-100" src="<%= image.url %>" alt="First slide">
          </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleFade<%= listing.id %>" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleFade<%= listing.id %>" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

    <div class="card-body">
      <div class="d-flex">
        <h5 class="card-title d-inline-block"><%= truncate(listing.title, length: 20) %></h5>
        <% if listing.verified == true %>
          <span class="badge badge-success d-inline-block h-100 mt-1 ml-2">Verified</span>
        <% end %>
      </div>
      <p class="card-text" style="font-size: 14px;"><%= truncate(listing.property_type, length: 75) %></p>

      <div class="d-flex">
        <a href= "<%=listing_path(listing.id)%>" class="btn btn-outline-primary btn-sm mb-3 d-inline">Read More</a></br>
        <% if current_user && current_user.superadmin? %>
          <% if listing.verified == false %>
            <%= link_to "Verify", verify_path(listing.id), method: :post, class: "btn btn-success btn-sm d-inline ml-2 h-100" %>
          <% else %>
            <%= link_to "Un-verify", verify_path(listing.id), method: :post, class: "btn btn-dark btn-sm d-inline ml-2 h-100" %>
          <% end %>
        <% end %>
      </div>

      <p class="card-text"><i class="fas fa-dollar-sign"></i> <strong>Price per Night:</strong> <%= listing.price_per_night %>0 RM</p>
      <p class="card-text"><i class="fas fa-users"></i> <strong>Max Guests:</strong> <%= listing.maximum_guests %></p>
      <% if current_user && (current_user.id == listing.user_id || current_user.moderator?) %>
        <%= link_to "Edit", edit_listing_path(listing.id), class: "btn btn-warning btn-sm mr-1" %>
        <%= link_to "Delete", listing_path(listing.id), class: "btn btn-danger btn-sm", method: :delete, :data => {:confirm => 'Are you sure you want to delete this listing?'} %>
      <% end %>
    </div>
  </div>
</div>
<% end %>
</a>

app/views/listings/edit.html.erb
<div class="jumbotron">
  <h2 class="text-center"> Edit Your Listing</h2>

  <div class="jumbotron">
    <%= form_with scope: :listing, url: listing_path, method: :patch, local: true do |form| %>

    <%= render partial: 'form', listings: @listing, object: form %>
    <div>
      <%= form.submit "Update Listing", class:"btn btn-warning"%>
    </div>
    <% end %>
    
  </div>

</div>

app/views/listings/index.html.erb
<%= render partial: "all_listings" %>

app/views/listings/search.html.erb
<h1 class="m-3">Filter Listings</h1>
<%= form_with scope: :listing, url: search_path, method: :post do |form| %>
<div class="jumbotron border border-warning">
  <div class="text-field mb-3 d-flex">
    <div class="container">
      <%= form.label "Search Term:" %>
      <%= text_field_tag "listing[multi]", nil, placeholder:"Where do you want to go today?", style:"width: 325px;", class:"form-control", value:"#{@searchTerm}" %>
    </div>
    <div class="container">
      <%= form.label "How many guests?" %></br>
      <%= form.select :maximum_guests, ["1", "2", "3",
        "4", "5", "6",
        "7", "8", "9",
        "10", "11", "12",
        "13", "14", "15",
        "16", "17", "18",
        "19", "20"
      ],
      class:"form-control" %></br>
    </div>
    <!-- <div class="container d-inline-block">
      <%#= form.label "How many bathrooms?" %></br>
      <%#= form.select :bathrooms, [
        "1 Bathroom", "2 Bathrooms", "3 Bathrooms",
        "4 Bathrooms", "5 Bathrooms", "6 Bathrooms",
        "7 Bathrooms", "8 Bathrooms", "9 Bathrooms",
        "10 Bathrooms"
      ],
      class:"form-control" %></br></br>
    </div> -->
    <!-- <div class="container d-inline-block">
      <%#= form.label "How many beds?" %></br>
      <%#= form.select :beds, [
        "1 Bed", "2 Beds", "3 Beds",
        "4 Beds", "5 Beds", "6 Beds",
        "7 Beds", "8 Beds", "9 Beds",
        "10 Beds"
      ],
      class:"form-control" %></br></br>
    </div> -->
  </div>

  <div class="text-field">
    <%= form.label "What amenities are you looking for?", class:"mb-2" %></br>
    <%= label_tag 'amenities', 'Essentials' %>
    <%= form.check_box :amenities, { multiple: true}, 'Essentials', nil %>
    <%= label_tag 'amenities', 'Wi-Fi', class:"ml-3" %>
    <%= form.check_box :amenities, { multiple: true}, 'Wi-Fi', nil %>
    <%#= label_tag 'amenities', 'Shampoo', class:"ml-3" %>
    <%#= form.check_box :amenities, { multiple: true }, 'Shampoo', nil %>
    <%#= label_tag 'amenities', 'Closet/Drawers', class:"ml-3" %>
    <%#= form.check_box :amenities, { multiple: true }, 'Closet/Drawers', nil %>
    <%#= label_tag 'amenities', 'TV', class:"ml-3" %>
    <%#= form.check_box :amenities, { multiple: true }, 'TV', nil %>
    <%#= label_tag 'amenities', 'Heat', class:"ml-3" %>
    <%#= form.check_box :amenities, { multiple: true }, 'Heat', nil %>
    <%#= label_tag 'amenities', 'Air Conditioning', class:"ml-3" %>
    <%#= form.check_box :amenities, { multiple: true }, 'Air Conditioning', nil %>
    <%#= label_tag 'amenities', 'Breakfast, Coffee, Tea', class:"ml-3" %>
    <%#= form.check_box :amenities, { multiple: true }, 'Breakfast, Coffee, Tea', nil %>
    <%#= label_tag 'amenities', 'Desk/Workspace' %>
    <%#= form.check_box :amenities, { multiple: true }, 'Desk/Workspace', nil%>
    <%#= label_tag 'amenities', 'Fireplace', class:"ml-3" %>
    <%#= form.check_box :amenities, { multiple: true }, 'Fireplace', nil%>
    <%#= label_tag 'amenities', 'Iron', class:"ml-3" %>
    <%#= form.check_box :amenities, { multiple: true }, 'Iron', nil %>
    <%#= label_tag 'amenities', 'Hair Dryer', class:"ml-3" %>
    <%#= form.check_box :amenities, { multiple: true }, 'Hair Dryer', nil %>
    <%#= label_tag 'amenities', 'Pets in the House', class:"ml-3" %>
    <%#= form.check_box :amenities, { multiple: true }, 'Pets in the House', nil %>
    <%#= label_tag 'amenities', 'Private Entrance', class:"ml-3" %>
    <%#= form.check_box :amenities, { multiple: true }, 'Private Entrance', nil %>
  </div>

  <!-- <div class="text-field">
    <%#= form.label :price_per_night %>
    <%#= form.text_field :price_per_night, class:"form-control" %></br>
  </div> -->

  <%= submit_tag "Filter Results", :name => nil, class:"btn btn-outline-info ml-3" %>
</div>
<% end %>

<div id="search_results">
  <%= render partial: 'search' %>
</div>

<div class="container d-flex justify-content-center mb-3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
      <div class="d-flex">
        <% count = 0 %>
        <% @paginate_count.times do %>
        <% count += 1 %>
        <li class="page-item"><a class="page-link" href="/?page=<%= count %>"><%= count %></a>
        <% end %>
      </div>
      <li class="page-item"><a class="page-link" href="/?page=<%= +1 %>">Next</a></li>
    </ul>
  </nav>
</div>

app/views/listings/search.js.erb
// empty the entire div
$('#search_results').empty()
$('#search_results').append("<%= j render 'search' %>")

app/views/listings/show.html.erb
<!-- Show Page for individual Listings -->
<div class="container-fluid d-flex mt-3">
  <div class="row">
    <div class="jumbotron col-8 d-inline border border-dark p-4">
      <h6>
        <%= @listing.property_type.upcase %></h6>
      <div class="d-flex">
        <h1 class="d-inline-block">
          <%= @listing.title %>
        </h1>
        <% if @listing.verified == true %>
          <h3 class="h-25 d-inline-block ml-3 mt-2">
            <span class="badge badge-success mb-5">Verified</span></h3>
        <% end %>
      </div>

      <h5 class="mb-4">
        <i class="fas fa-map-marked-alt mb-2"></i>
        <strong>Country/Region:
        </strong>
        <%= @listing.city %>,
        <%= @listing.country %>
      </h5>

      <div id="carouselExampleFade<%= @listing.id %>" class="carousel slide carousel-fade" data-ride="carousel" data-interval="5000">
        <div class="carousel-inner">
          <% @listing.images.each_with_index do |image, i| %>
            <div class="carousel-item <%= " active" if i == 0 %>">
              <img class="d-block w-100" src="<%= image.url %>" alt="First slide">
            </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleFade<%= @listing.id %>" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleFade<%= @listing.id %>" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </br>
    <h6>
      <%= @listing.description %>
    </h6>
  </br>
  <h4>
    <i class="fas fa-dollar-sign"></i>
    <strong>Price per night:</strong>
    <%= @listing.price_per_night %>0 RM</h4>
</br>

<%# if @listing.bookings.payment_status == paid %>
  <%= link_to "Leave a review", new_listing_review_path(listing_id: @listing.id), class:"btn btn-outline-warning" %>
  <%# end %>

    <hr class="my-4">

    <div class="container justify-content-center">
      <!-- <div class="d-inline-block mr-5"> -->
      <div class="d-inline-block mr-5 mb-3">
        <div class="d-inline-block mr-3">
          <h5>
            <i class="fas fa-home"></i>
            <strong>Home Type:</strong>
            <%= @listing.home_type %></h5>
        </div>
        <div class="d-inline-block mr-3">
          <h5>
            <i class="fas fa-users"></i>
            <strong>Max. Guests:</strong>
            <%= @listing.maximum_guests %></h5>
        </div>
        <div class="d-inline-block mr-3">
          <h5>
            <i class="fas fa-bed"></i>
            <strong>Beds:</strong>
            <%= @listing.beds %></h5>
        </div>
        <div class="d-inline-block">
          <h5>
            <i class="fas fa-bath"></i>
            <strong>Bathrooms:</strong>
            <%= @listing.bathrooms %></h5>
        </div>
      </div>

      <div class="d-inline-block">
        <h5 class="mb-2">
          <i class="fas fa-wine-glass-alt"></i>
          <strong>Amenities:</strong>
          <% @listing.amenities.each do |amenity| %>
            •
            <%= amenity %>
          <% end %>
        </h5>
        <h5>
          <i class="fas fa-hot-tub"></i>
          <strong>Shared Spaces:</strong>
          <% @listing.shared_spaces.each do |space| %>
            •
            <%= space %>
          <% end %>
        </h5>
      </div>
    </div>

    <hr class="my-4">

    <div class="container d-flex">
      <h1 class="mb-4 d-inline"><%= @listing.reviews.count %>
        Reviews |
      </h1>
      <% if @reviews.count > 0 %>
        <h4 class="mt-3 ml-2">Average Rating:
          <%= (@reviews.sum(&:rating).to_f / @reviews.count.to_f).round(1) %>
          / 5.0</h4>
      <% else %>
        <h4 class="mt-3 ml-2">Average Rating: 0 / 5.0</h4>
      <% end %>
    </div>
    <% @listing.reviews.each do |review| %>
      <div class="container mb-3">
        <h4><%= review.user.first_name %>
        </h4>
        <p><%= review.created_at %></p>
        <p><%= review.comment %></p>
        <p>
          <strong>Rating:
          </strong><%= review.rating %>/5</p>
        <hr class="my-4">
      </div>
    <% end %>
  </div>
  <div class="col-4 d-inline">
    <div id="booking-sidebar" class="card p-4 border border-dark bg-light sticky-top sticky-offset">
      <h3 class="text-center">Like this? Request to Book.</h3>
    </br>
    <div class="text-center d-flex justify-content-center">

      <%= form_with url: bookings_path(listing_id: @listing.id), local: true do |form| %>
      <div class="text-field">
        <%= form.label "When do you want to check-in?" %>
        <%= form.date_field :check_in, class:"datePicker border border-primary text-center form-control", placeholder:"Select your check-in date"%></br>
    </div>

    <div class="text-field" style="width: 300px;">
      <%= form.label "When do you want to check-out?" %>
      <%= form.date_field :check_out, class:"datePicker border border-primary text-center form-control", placeholder:"Select your check-out date"%></br>
  </div>

  <div class="text-field mb-3">
    <%= form.label "Number of Guests:" %></br>
  <%= form.select :guests_count, ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" ], class:"form-control" %></br>
</div>

<div>
<%= form.submit "Request Booking", class:"btn btn-danger"%>
</div>

<% end %>
</div>
</div>
</div>

</div>
</div>