config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  # Home Page - Index
  root 'pages#index'

  # Signing in
  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"

  # Creating a new account
  get "/sign_up" => "users#new", as: "sign_up"
  post "/sign_up" => "users#new"

  # Current Users profile page
  get "/profile" => "users#profile" #own dashboard
  get "/profile/:id" => "users#profile/:id"

  # Get/Show create a listing page
  get "/listings/new" => "listings#new"

  get "/listings/autofill" => "listings#autofill"

  # Get search results
  post "/listings/search" => "listings#search", as: "search"
  get "/listings/search" => "listings#search_form", as:"search_form"

  # Get/Show individual listing page
  get "/listings/:id" => "listings#show"

  # Braintree Checkout Route incl. wildcard [T]
  post 'braintree/:booking_id/checkout' => 'braintree#checkout', as: 'braintree_checkout'


  # Get/Show new review page
  # get "/reviews/new" => "reviews#new"
  # post "/reviews/create" => "reviews#create"



  # Other Users profile page - looking at someone else's profile, basic information
  get "/users/:id" => "users#show"

  # Verifying a listing
  post "/verify/:id" => "listings#verify", as: "verify"

  # Google OAuth2.0 callback route
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, :bookings

  resources :listings do
    resource :review, only: [:new, :create, :destroy]
  end

  resources :bookings do
    resources :brain_tree_new
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  # validates :password, optional: true

  has_many :listings, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :authentications, dependent: :destroy

  enum role: [:customer, :moderator, :superadmin]
  mount_uploader :avatar, AvatarUploader
  # Enum refers to the Ruby class we're using
  # role is the attribute we're going to treat as an enum
  # :customer etc, names we're using to reference a users role

  # for every new account set default role to :customer
  after_initialize do
    if self.new_record?
      self.role ||= :customer
    end
  end

  # Manually assign superadmin/moderators by:
  # rails c -> x = User.firnd(:id) -> x.superadmin! (to assign)
  # Output => x.role = "superadmin"

  def self.create_with_auth_and_hash(authentication, auth_hash)
    # byebug to check what auth_hash["info"] is for params from Google
    user = self.create!(
      first_name: auth_hash["info"]["first_name"],
      last_name: auth_hash["info"]["last_name"],
      email: auth_hash["info"]["email"],
      password: SecureRandom.hex(10)
      # since the user will use their google password, set secure random for password field
    )
    user.authentications << authentication
    return user
  end

  # grab google token to access google for user data
  def google_token
    x = self.authentications.find_by(provider: 'google_oauth2')
    return x.token unless x.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_action :set_user, only: [:edit, :update, :destroy]

  def profile
    @user = current_user
    @booking = current_user.bookings
    @listing = current_user.listings
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Your account has been successfully created."
      redirect_to sign_in_path
    else
      flash[:error] = "Failed to create an account. Please try again."
      redirect_to sign_up_path
    end
  end

  def new
    @user = User.new
  end


  def update
    @user = User.find(params[:id])
    @user.update(user_update_params)
    if @user.save
      flash[:success] = "Your information was successfully updated."
      redirect_to profile_path
    else
      flash[:error] = "Your user details could not be updated. Please try again."
      redirect_to profile_path
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_from_params
      email = user_params.delete(:email)
      password = user_params.delete(:password)
      first_name = user_params.delete(:first_name)
      last_name = user_params.delete(:last_name)
      avatar = user_params.delete(:avatar)

      Clearance.configuration.user_model.new(user_params).tap do |user|
        user.email = email
        user.password = password
        user.first_name = first_name
        user.last_name = last_name
        user.avatar = avatar
      end
    end

    def user_params
      params.require(:user).permit(:first_name, :password, :last_name, :email, :avatar)
    end

    def user_update_params
      params.require(:user).permit(:first_name, :password, :last_name, :email, :avatar)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bookings.html.erb
<h1 class="mb-4">My Bookings</h1>
<% if current_user.bookings != [] %>
  <% current_user.bookings.each_with_index do |booking, i| %>
    <div id="booking-id-<%= booking.id %>" class="card mb-3 w-25 mr-3 d-inline-block border border-dark">
      <div class="card-header bg-dark text-center text-white">
        <h5>
          <strong>Booking
            <%= i+1 %></strong>
        </h5>
      </div>
      <div class="card-body text-center">
        <!-- Issue here when user has less than 2 listings, sometimes happens on third -->
        <!-- Was because of listing[i] index. Should be booking.listing.title etc -->
        <h5 class="card-title">
          <%= truncate(booking.listing.title, length: 40) %>
        </h5>
        <%= image_tag(booking.listing.images[0].thumb.url) %>
        <p class="card-text mt-3">
          <%= booking.listing.city %>,
          <%= booking.listing.country%></p>
        <p>
          <strong>Check-in:</strong>
          <%= booking.check_in %></p>
        <p>
          <strong>Check-out:</strong>
          <%= booking.check_out %></p>
        <p>
          <strong>Guests:</strong>
          <%= booking.guests_count %></p>
        <% if booking.pending? %>
          <%= link_to "Make Payment", braintree_new_path(booking_id: booking.id), class:"btn btn-success mb-3" %>
        <% else %>
          <%= link_to "Payment Made", braintree_new_path(booking_id: booking.id), class:"btn btn-success disabled mb-3" %>
        <% end %>
        <div class="container d-flex justify-content-center">
          <%= link_to 'Cancel this Booking', booking_path(booking), method: :delete, remote: true, class: 'btn btn-danger booking-delete', value: booking.id, data: {confirm: 'Are you sure you want to delete this booking?'} %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="container text-center">
    <h5 class="text-center">You don't seem to have any bookings yet.</h5>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container d-inline">
  <div class="text-field">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email',  class:"form-control"%>
  </div>

  <div class="password-field">
    <%= form.label :password %>
    <%= form.password_field :password, class:"form-control"%>
  </div>

  <div class="text-field">
    <%= form.label :first_name%>
    <%= form.text_field :first_name, class:"form-control"%>
  </div>

  <div class="text-field">
    <%= form.label :last_name%>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="file_field">
    <%= form.label "Upload a Profile picture", class:"mt-3" %></br>
    <%= form.file_field :avatar %>
  </div>

  <hr class="my-4">
  <% if current_user %>
  <div>
    <%= form.submit class:"btn btn-warning mt-2", method: :update, value:"Update information" %>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <div class="container mt-3">
    <div class="jumbotron">
      <h2 class="m-2"><%= t(".title") %></h2>

      <%= form_for @user do |form| %>
      <%= render partial: '/users/form', object: form %>

      <div class="submit-field">
        <%= form.submit class:"btn btn-success" %>
      </div>

      <div class="other-links">
        <%= link_to t(".sign_in"), sign_in_path %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container">

  <div class="jumbotron mt-3 border border-dark">
    <div class="rounded-circle card-img-top">
      <% if @user.avatar? %>
        <img src="<%= @user.avatar.url %>" alt="" class="rounded-circle w-25">
      <% end %>
    </div>
    <h1 class="display-4">Hello,
      <em><%= @user.first_name %>
        <%= @user.last_name %></em>
    </h1>
    <p class="lead">Welcome to your dashboard. You can
      <strong>view and edit your current listings and bookings</strong>, and
      <strong>edit your account information.</strong>
    </p>
    <hr class="my-4">
    <% if @user.role == "superadmin" %>
      <p>
        <strong>Account Level:
        </strong>
        <span class="badge badge-dark"><%= @user.role%></span>
      </p>
      <% elsif @user.role == "moderator" %>
        <p>
          <strong>Account Level:
          </strong>
          <span class="badge badge-warning"><%= @user.role%></span>
        </p>
      <% else %>
        <p>
          <strong>Account Level:
          </strong>
          <span class="badge badge-primary"><%= @user.role%></span>
        </p>
      <% end %>

      <%= form_for @user do |form| %>
      <%= render partial: '/users/form', object: form %>
    <% end %>
  </div>

  <div class="jumbotron border border-dark">
    <h1 class="mb-4">My Listings</h1>
    <% if current_user.listings != [] %>
      <% current_user.listings.each_with_index do |listing, i| %>
        <div class="card mb-3 border border-info">
          <div class="card-header">
            <p>
              <strong>Listing
                <%= i+1 %></strong>
            </p>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= listing.title %></h5>
            <p class="card-text"><%= listing.description %></p>
            <%= image_tag(listing.images[0].thumb.url) %>
            <p class="card-text">RM
              <%= listing.price_per_night %>0</p>
            <%= link_to "Edit", edit_listing_path(listing.id), class: "btn btn-warning btn-sm mr-1" %>
            <%= link_to "Delete", listing_path(listing.id), class: "btn btn-danger btn-sm mr-1", method: :delete, :data => {:confirm => 'Are you sure you want to delete this listing?'} %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="container text-center">
        <h5 class="text-center">You don't seem to have any listings yet.</h5>
      </div>
    <% end %>
  </div>

  <div id="my-bookings" class="jumbotron border border-dark">
    <%= render partial: "bookings" %>
  </div>
</div>