config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  # Home Page - Index
  root 'pages#index'

  # Signing in
  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"

  # Creating a new account
  get "/sign_up" => "users#new", as: "sign_up"
  post "/sign_up" => "users#new"

  # Current Users profile page
  get "/profile" => "users#profile" #own dashboard
  get "/profile/:id" => "users#profile/:id"

  # Get/Show create a listing page
  get "/listings/new" => "listings#new"

  get "/listings/autofill" => "listings#autofill"

  # Get search results
  post "/listings/search" => "listings#search", as: "search"
  get "/listings/search" => "listings#search_form", as:"search_form"

  # Get/Show individual listing page
  get "/listings/:id" => "listings#show"

  # Braintree Checkout Route incl. wildcard [T]
  post 'braintree/:booking_id/checkout' => 'braintree#checkout', as: 'braintree_checkout'


  # Get/Show new review page
  # get "/reviews/new" => "reviews#new"
  # post "/reviews/create" => "reviews#create"



  # Other Users profile page - looking at someone else's profile, basic information
  get "/users/:id" => "users#show"

  # Verifying a listing
  post "/verify/:id" => "listings#verify", as: "verify"

  # Google OAuth2.0 callback route
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, :bookings

  resources :listings do
    resource :review, only: [:new, :create, :destroy]
  end

  resources :bookings do
    resources :brain_tree_new
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
  end

  def new
    @reviews = Review.all.order(created_at: :desc)
  end

  def create
    @listing = Listing.find(params[:listing_id])
    @review = Review.new(review_params)
    @review.listing_id = @listing.id
    @review.user_id = current_user.id
    if @review.user_id != @listing.user_id
      if @review.save
        flash[:success] = "Your review was successfully created."
        redirect_to listing_path(@listing.id)
      else
        flash[:error] = "Failed to create your review."
        redirect_to listing_path(@listing.id)
      end
    else
      flash[:error] = "You can't review your own listing!"
      redirect_to listing_path(@listing.id)
    end
  end

  def show
  end

  def destroy
  end

  private
  def review_params
    params.permit(:comment, :rating, :listing_id, :user_id)
  end

end

app/views/reviews/new.html.erb
<div class="container d-flex justify-content-center">
  <div class="jumbotron border border-dark mt-5 w-75">
    <h2 class="text-center mb-5">Review this listing</h2>
    <div class="text-field mb-3 d-flex justify-content-center">
      <%= form_with url: listing_review_path, method: :post, local: true do |form| %>
      <%= form.label "How many stars would you give your stay?"%></br>
      <div class="container d-flex justify-content-center">
        <%= form.select :rating, [
          "1 Star", "2 Stars", "3 Stars",
          "4 Stars", "5 Stars"
        ],
        class:"form-control"%></br>
      </div>
    </div>

    <div class="text-area text-center">
      <%= form.label "Leave your Review:", class:"mt-2" %>
      <%= form.text_area :comment, class:"form-control text-center", rows:"5", placeholder:"Tell other guests how your experience was" %></br>
    </div>
    <div class="container d-flex justify-content-center">
      <%= form.submit "Create Review", class:"btn btn-success"%>
    </div>
    <% end %>
  </div>
</div>