config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  # Home Page - Index
  root 'pages#index'

  # Signing in
  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"

  # Creating a new account
  get "/sign_up" => "users#new", as: "sign_up"
  post "/sign_up" => "users#new"

  # Current Users profile page
  get "/profile" => "users#profile" #own dashboard
  get "/profile/:id" => "users#profile/:id"

  # Get/Show create a listing page
  get "/listings/new" => "listings#new"

  get "/listings/autofill" => "listings#autofill"

  # Get search results
  post "/listings/search" => "listings#search", as: "search"
  get "/listings/search" => "listings#search_form", as:"search_form"

  # Get/Show individual listing page
  get "/listings/:id" => "listings#show"

  # Braintree Checkout Route incl. wildcard [T]
  post 'braintree/:booking_id/checkout' => 'braintree#checkout', as: 'braintree_checkout'


  # Get/Show new review page
  # get "/reviews/new" => "reviews#new"
  # post "/reviews/create" => "reviews#create"



  # Other Users profile page - looking at someone else's profile, basic information
  get "/users/:id" => "users#show"

  # Verifying a listing
  post "/verify/:id" => "listings#verify", as: "verify"

  # Google OAuth2.0 callback route
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, :bookings

  resources :listings do
    resource :review, only: [:new, :create, :destroy]
  end

  resources :bookings do
    resources :brain_tree_new
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'https://use.fontawesome.com/releases/v5.4.2/css/all.css' %>
  <%= stylesheet_link_tag    'https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css' %>
  <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'%>
  <%= stylesheet_link_tag    'https://npmcdn.com/flatpickr/dist/themes/airbnb.css'%>

  <%= javascript_include_tag 'https://js.braintreegateway.com/web/3.6.3/js/client.min.js' %>
  <%= javascript_include_tag 'https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js' %>
  <%= javascript_include_tag "https://code.jquery.com/jquery-3.3.1.js" %>
  <%#= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/shortcuts/sticky.js" %>
  <%#= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js" %>
  <%#= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/shortcuts/infinite.js" %>
  <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/flatpickr' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js' %>
  <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js' %>
  <!-- Load external CDN's first, then load local application -->
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>

  <%= csrf_meta_tag %>
  <title>ScamBnB: Plan your Vacation</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom border-top border-dark">
    <i class="text-black fas fa-running"></i> <%= link_to "ScamBnB", root_path, class: "navbar-brand text-danger" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Use justify-content-between for this layout -->
    <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <!-- <form class="form-inline">
          <input class="form-control mr-sm-2" style="width: 325px;" type="search" placeholder="Where do you want to go?" aria-label="Search">
          <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Let's Go!</button>
        </form> -->
        <%= form_tag search_path, method: :post, class:"form-inline" do %>
          <%= text_field_tag "listing[multi]", nil, placeholder:"Where do you want to go today?", style:"width: 325px;", class:"form-control border border-dark", id:"main-search", list:"autofill"%>
          <datalist id="autofill"></datalist>
          <%= submit_tag "Search", :name => nil, class:"btn btn-outline-primary ml-3" %>
        <% end %>
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Become a Host", new_listing_path, class: "nav-link" %>
        </li>
        <% if !signed_in? -%>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "nav-link text-warning" %>
          </li>
        <% else -%>
          <li class="nav-item">
            <%= link_to "My Profile", profile_path, class: "nav-link mr-2" %>
          </li>
        <% end %>

        <div id="header">
          <% if signed_in? -%>
          <%= button_to t(".sign_out"), sign_out_path, method: :delete, class:"btn btn-outline-danger my-2 my-sm-0"%>
          <% else -%>
          <%= link_to "Sign in with Google+", "/auth/google_oauth2", class:"btn btn-outline-primary my-2 my-sm-0" %>
          <% end -%>
        </div>
      </ul>
    </div>
  </nav>
  <!-- SUPER PIECE OF NIFTY CODE FOR HANDLING CUSTOM FLASH MESSAGES. REFER TO APPLICATION HELPER -->
  <div id="flash">
    <% flash.each do |key, value| -%>
    <div class="container mx-auto">
      <div class="<%= flash_class(key) %> mt-3 text-center" id="flash_<%= key %>"><%= h value %></div>
    </div>
    <% end %>
  </div>

  <div class="container-fluid">
    <%= yield %>
  </div>

  <footer class="footer bg-dark h-100">
    <p class="text-center text-white">ScamBnB Inc. 2018 &copy All rights reserved</p>
  </footer>

</body>
</html>